name: Build and Lint

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Lint
        uses: ./.github/actions/build-and-lint
        with:
          node-version: '18.20.3'
